### PR TITLE
Allow MarkdownIt plugins to be supplied as Strings rather than functions

### PR DESCRIPTION
**Pull request by jasononeil**
This enables us plugins to be set in Webpack v1 where configuration can only be given as JSON serialisable values, so functions don't work.

(Reason I'm still using Webpack v1: I'm using Gatsby as a static site generator and they haven't upgraded yet)

### CODE REVIEW

**Comment by jasononeil** [comment]
Well, I tried to add a fixture to test that we have coverage on the "specifying MarkdownIt plugins as strings" functionality, but I'm having trouble reading the diff in the Jest snapshot file to see if it's had adverse affects. Does it seem okay to you @ticky or does the giant snapshot diff mean I've broken something?

It's still working well for me on my local tests

**Comment by ticky** [comment]
The giant snapshot diff is really difficult to understand, sorry about that. I got a bit over-excited at the potential and unfortunately it’s gotten a bit out of hand.

I’ve moved your additional spec to be its own individual spec, which now means there’s only a single block addition to the snapshot, which is a bit more clear. Your code didn’t break anything - good stuff!

I’ve updated the Readme a bit, but I don’t have a Webpack 1.x project on hand to test - can you confirm whether you can use `require.context` alone, or a combination of `path.relative` and `require.resolve` as in the spec? I’ve added a paragraph about this: <https://github.com/jasononeil/markdown-component-loader/tree/53c2a489fc04ff98b8d4e09f1a42c5aaf11d7818#legacy-webpack-compatibility>

**Review by ticky — APPROVED** [review]
Pending confirmation that the readme does not lie, I’m feeling happy to merge this and cook you up a release with it! 😄

**Comment by jasononeil** [comment]
Thanks for the clean-up, so much better! (And sorry it's taken me so long to get back to you).

I can confirm that the README is correct and is working on my Webpack 1 Gatsby project.

Thanks again, looking forward to the release so I can stop having a git-fork in my package.json 😄

**Comment by ticky** [comment]
Thanks for the confirmation! I’ll get this cooked up into a release imminently so you can update your references :)

**Comment by ticky** [comment]
Just published in [v1.1.0](https://github.com/ticky/markdown-component-loader/releases/tag/v1.1.0). :)

**Comment by jasononeil** [comment]
:tada: thank you!!!

**Pull request merged**
