### PR TITLE
🚪 Allow plain JSX in Markdown, handle self-closing tags

### LINKED ISSUE #5: Doesn't handle self-closing JS(X)HTML tags within Markdown

### LINKED ISSUE #6: `elementProps` should take precedence over generated props

### LINKED ISSUE #10: Maybe get rid of double-brace syntax?
Hey I just stumbled upon this and am using [markdown-it-jsx](https://github.com/osnr/markdown-it-jsx) at the moment. 

How are your thoughts about the double brace syntax?
I'd really like to use native JSX without any extra syntax within markdown. 
Would you be interested in PRs in that direction?

### PR DESCRIPTION
**Pull request by ticky**
This pull request updates the JSX preprocessing logic rather significantly. This will be a serious API change. I will initially publish it as a pre-release on track for v1.0.0.

First of all, it stops using `htmltojsx`. It makes too many assumptions about the conversion, and requires far too much dancing around the fact that it passes your input to an actual DOM implementation which is incompatible with JSX sensibilities. It required, while I was working on this, hiding React element names, parameter names, and parameter assignment expressions, in order to process successfully.

Now that it’s been removed, and `markdown-it` patched to accept JSX-style names, we need only shield parameter assignment expressions. The removal also means we don’t have to do extra processing of void elements to avoid React warnings. Now, a valid JSX element is a valid JSX element within our Markdown, and vice versa!

It is now possible to use JSX (or HTML!) elements directly from within the mdx document, double-curly-brace assignment expressions not required. Double-curly-brace assignment expressions remain the expected way to interpolate values into markdown text, however.

I’ve also taken the opportunity to simplify our spec output somewhat. The query string tests have been removed, as they’re no longer technically supported by Webpack 2. Likewise, we’ve stopped testing the exact code output of the component, instead taking the “preamble” (everything before the function begins) and the resultant React structure. This should mean less spec churn between versions and feature changes when the output doesn’t visibly change for the end-user!

- [x] Fix behaviour for self-closing basic HTML tags, by passing them to HTMLtoJSX as valid HTML (fixes #5)
- [x] Put `elementProps` at end of tags (fixes #6)
- [x] Make it possible to use JSX components outside the protection of assignment expressions
  - [x] Allow non-alphanumeric element names to survive conversion (i.e. `<MarkdownComponent.HiMom />` _should_ work)
  - [x] Make sure JSX component Object props are not changed by the JSX double-bracket interpolator (fixes #10 (we’re not getting rid of the syntax but you will need it in fewer places))
  - [x] Fix case-sensitive props

### CODE REVIEW

**Comment by Xiphe** [comment]
in my local app, the following statements render weirdly:

- [ ] `<Foo style={1} />`
- [ ] `<Foo style={ { background: 'blue' } } />`
- [ ] `<Foo { ...props } />`
- [ ] `<Foo {...{ ...props, bar: 'baz' }} />`

I'll try to fix them and propose the changes here

**Comment by ticky** [comment]
Yeah, I noticed that there was some weird behaviour. The choice of the double brace assignment expression has come at the cost of braces inside tags being awkward.

Two things of note;

1. HTMLtoJSX only has a special case for the “style” prop, and I only have a special case for it myself (hiding it from HTMLtoJSX) - ideally, _any_ property expressions should be preserved!
2. The method of those special cases is probably very flaky! There be dragons! :dragon:

Hope you come up with something that works for you! :smile:

**Comment by ticky** [comment]
It occurs to me `<Foo ...props />` would likely _also_ be flaky… oh no

**Comment by ticky** [comment]
Sorry it’s been so long between comms on this one. Maybe I should try to break what stuff doesn’t break anything in real-world use out of this so it’s a smaller target, with fewer moving parts.

**Comment by Xiphe** [comment]
Hey @ticky 

Sorry I also did not managed to do s.th. here :(
This is currently not on my plate anymore

**Comment by ticky** [comment]
That’s okay! It’s funny, the current version is serving our current needs, but not my lofty goals just yet. Hopefully I can get back to polishing this off someday soon, though :)

**Comment by ticky** [comment]
Ah, well, `<Foo …props/>` isn’t valid anyway, so, oh well :P

I’ve rebased this atop current master, it got a little dusty!

**Comment by Xiphe** [comment]
🚀 ❤️

**Pull request merged**
